### PR TITLE
Api update

### PR DESCRIPTION
**Pull request by airguru**

### CODE REVIEW

**Comment by airguru** [comment]
All the most pressing issues should be done. Please test.

**Review by PedroRossa98 — APPROVED** [review]
I'm steal testing but for now is all good.
image

Can we add a column with a pulldown list of protocols and a unic Run button.

**Comment by PedroRossa98** [comment]
we will need to add on the readme the process to add the static files to the web server, I think is this: 
python manage.py collectstatic

**Comment by PedroRossa98** [comment]
/apparatus/{id} should give the configuration on the apparatus table too. 

image

**Pull request merged**
